# Generated by Django 6.0.2 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful AI assistant.'),
        ),
    ]
