# Generated by Django 6.0.2 on 2026-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_chatbot_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='allowed_domains',
            field=models.TextField(default='*', help_text='Comma-separated list of allowed domains (e.g. example.com, mysite.org). Use * for all.'),
        ),
    ]
