# Generated by Django 6.0.2 on 2026-02-09 09:22

import chatbots.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_chatbot_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='secret_key',
            field=models.CharField(default=chatbots.models.generate_secret_key, editable=False, help_text='Secret Key for backend verification', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='widget_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public Key for the widget'),
        ),
    ]
