# Generated by Django 6.0.2 on 2026-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_chatbot_is_active_chatbot_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='published_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
