# Generated by Django 6.0.2 on 2026-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_chatbot_published_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bot_prompt_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for system prompt, personality, fallback, and guardrails.'),
        ),
    ]
