# Generated by Django 5.1.12 on 2026-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0006_chatbot_bot_prompt_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='selected_llm',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], default='gemini', max_length=50),
        ),
    ]
