# Generated by Django 6.0.2 on 2026-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0007_alter_chatbot_selected_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bot_type',
            field=models.CharField(choices=[('sales', 'Sales Bot'), ('support', 'Support Bot'), ('marketing', 'Marketing Bot'), ('faq', 'FAQ Bot'), ('custom', 'Custom Bot')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='fallback_behavior',
            field=models.TextField(blank=True, help_text="What to say when the bot doesn't know the answer"),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='personality',
            field=models.TextField(blank=True, help_text='The personality of the bot (e.g. friendly, professional)'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='tone',
            field=models.CharField(blank=True, help_text='The tone of the bot (e.g. formal, casual)', max_length=100),
        ),
    ]
