# Generated by Django 6.0.3 on 2026-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0008_chatbot_bot_type_chatbot_fallback_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='formatting_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for response formatting (markdown, code_highlight, tables, etc.)'),
        ),
    ]
