# Generated by Django 6.0.3 on 2026-04-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        ('chatbots', '0009_chatbot_formatting_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_services.providerconfiguration'),
        ),
    ]
