# Generated by Django 6.0.2 on 2026-02-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='visitor_id',
            new_name='visitor_identifier',
        ),
        migrations.AddField(
            model_name='message',
            name='latency',
            field=models.FloatField(blank=True, help_text='Latency in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the response (e.g. knowledge, ai_api)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='token_usage',
            field=models.IntegerField(default=0, help_text='Total tokens used for this response'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conversations.visitor'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.visitor'),
        ),
    ]
