# Generated by Django 6.0.2 on 2026-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_session_visitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
