# Generated by Django 6.0.2 on 2026-02-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence score of the knowledge retrieval (0-1)', null=True),
        ),
    ]
