services:
  - type: web
    name: botman-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn botman_backend.wsgi:application"
    healthCheckPath: /api/health/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: botman_backend.settings.base
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "botman-api.onrender.com,localhost,127.0.0.1"
      - key: REDIS_URL
        value: "redis://localhost:6379/1"
      - key: CELERY_BROKER_URL
        value: "redis://localhost:6379/0"
