# Generated by Django 6.0 on 2026-03-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0008_chatbot_bot_type_chatbot_fallback_behavior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_bot_token_encrypted', models.CharField(max_length=512, unique=True)),
                ('telegram_bot_username', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_integration', to='chatbots.chatbot')),
            ],
        ),
    ]
