# Generated by Django 6.0.2 on 2026-02-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge_files/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='processing', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chatbots.chatbot')),
            ],
        ),
    ]
