# Generated by Django 6.0.2 on 2026-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgefile_chunk_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
    ]
