# Generated by Django 5.1.12 on 2026-02-09 11:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledgechunk_chunk_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
