# Generated by Django 6.0.2 on 2026-02-10 07:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0008_chatbot_bot_type_chatbot_fallback_behavior_and_more'),
        ('knowledge', '0006_alter_knowledgechunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_k_search__e62644_gin'),
        ),
    ]
