# Generated by Django 6.0.2 on 2026-02-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_tokenusage'),
        ('chatbots', '0005_chatbot_published_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_messages', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('avg_latency', models.FloatField(default=0.0, help_text='Average latency in ms')),
                ('total_tokens', models.IntegerField(default=0)),
                ('knowledge_hit_rate', models.FloatField(default=0.0, help_text='Percentage of messages from knowledge base (0-100)')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='chatbots.chatbot')),
            ],
            options={
                'verbose_name_plural': 'Bot Analytics Daily',
                'unique_together': {('chatbot', 'date')},
            },
        ),
    ]
