# Generated by Django 6.0.2 on 2026-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('category', models.CharField(choices=[('AI', 'AI Service'), ('EMBEDDING', 'Embedding Service'), ('WIDGET', 'Widget'), ('SYSTEM', 'System'), ('DB', 'Database')], default='SYSTEM', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'category'], name='monitoring__level_0de706_idx'), models.Index(fields=['created_at'], name='monitoring__created_e95237_idx')],
            },
        ),
    ]
